In [ ]:
# NASH #

In [ ]:
### 1- representing games ###

In [ ]:
# instal nashpy

In [51]:
pip install nashpy #instal library

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#instal'


In [10]:
import nashpy as nash #import library

In [12]:
nash.__version__ #version

'0.0.41'

In [20]:
A= [[3,1],[0,2]]
print(A)
B= [[2,1],[0,3]]
print(B)

[[3, 1], [0, 2]]
[[2, 1], [0, 3]]


In [23]:
game1=nash.Game(A,B) #now game1 is an object

In [24]:
game1

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [25]:
A= [[1,-1],[-1,1]]
print(A)
B= [[-1,1],[1,-1]]
print(B)

[[1, -1], [-1, 1]]
[[-1, 1], [1, -1]]


In [28]:
matching_pennies=nash.Game(A,B) #now matching pennies is an object, in this game if i win you lose

In [27]:
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [ ]:
### 2- utilities ###

In [31]:
import numpy as np

In [34]:
A= [[1,-1],[-1,1]]
print(A)

[[1, -1], [-1, 1]]


In [37]:
matching_pennies1=nash.Game(A) #now matching pennies is an object, in this game if i win you lose
matching_pennies1 #works even if i don't specified the column player

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [ ]:
# distribution

In [49]:
sigma_row=np.array([.8, .2])
print(sigma_row)

sigma_col=np.array([0.6, 0.4])
print(sigma_col)

[0.8 0.2]
[0.6 0.4]


In [50]:
matching_pennies1[sigma_row,sigma_col]

array([ 0.12, -0.12])

In [ ]:
### 3- Nash Equilibrium ###

In [90]:
A=np.array([[1,1,-1],[2,-1,0]])
print(A)

B=np.array([[1/2,-1,-1/2],[-1,3,2]])
print(B)

[[ 1  1 -1]
 [ 2 -1  0]]
[[ 0.5 -1.  -0.5]
 [-1.   3.   2. ]]


In [91]:
game=nash.Game(A,B) #define the game
game

Bi matrix game with payoff matrices:

Row player:
[[ 1  1 -1]
 [ 2 -1  0]]

Column player:
[[ 0.5 -1.  -0.5]
 [-1.   3.   2. ]]

In [92]:
NE=game.support_enumeration()
NE

<generator object support_enumeration at 0x000001FAF818D6D0>

In [93]:
type(NE)

generator

In [94]:
for eq in NE:
    print(eq)

(array([0.66666667, 0.33333333]), array([-0.        ,  0.33333333,  0.66666667]))


In [97]:
NE=game.vertex_enumeration()

In [98]:
list(NE)

[(array([0.66666667, 0.33333333]),
  array([1.85037171e-17, 3.33333333e-01, 6.66666667e-01]))]

In [ ]:
### 4- Lemke Howson algorithm ###

In [100]:
A=np.array([[3, 1],[0, 2]])
print(A)

B=np.array([[2, 1],[0, 3]])
print(B)

[[3 1]
 [0 2]]
[[2 1]
 [0 3]]


In [103]:
game=nash.Game(A,B)
game

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [105]:
game.lemke_howson(initial_dropped_label=0)

(array([1., 0.]), array([1., 0.]))

In [106]:
for label in range(4):
    print(game.lemke_howson(initial_dropped_label=0))

(array([1., 0.]), array([1., 0.]))
(array([1., 0.]), array([1., 0.]))
(array([1., 0.]), array([1., 0.]))
(array([1., 0.]), array([1., 0.]))


In [108]:
NE=game.lemke_howson_enumeration()

In [109]:
list(NE)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.]))]

In [110]:
for eq in game.support_enumeration():
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.75, 0.25]), array([0.25, 0.75]))


In [ ]:
### 5- repeated games ###