In [ ]:
# Numerical Pithon

In [2]:
import numpy as np #import numpy and rename it in np

In [3]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [4]:
print(arr_1d)

[1 2 3 4 5]


In [5]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d arra

In [5]:
print(arr_1d < 3) #RETURN BOOLEAN VALUES only 21<3 and 2<3

[ True  True False False False]


In [6]:
print(arr_1d[arr_1d < 3]) #FILTER: RETURN ARRAY ELEMENTS THAT MEET THE CONDITION

[1 2]


In [4]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(arr_2d < 3)


[[ True  True False False]
 [False False False False]
 [False False False False]]


In [10]:
np.where(arr_2d < 4, 1, 0) #if True -> 1 else 0
# (nella matrice cerca <4, se vero =1, se falso =0)


array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:

A = np.random.rand(10, 10) #RANDOM RAND: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].
a = A.tolist()

In [15]:
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

CPU times: total: 0 ns
Wall time: 1.02 ms


49.35

In [16]:
%%time
round(np.sum(A), 2)

CPU times: total: 0 ns
Wall time: 12 ms


49.35

In [18]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [19]:
a+b #addition

array([5, 7, 9])

In [20]:
a-b #subtraction

array([-3, -3, -3])

In [21]:
a*3 #scalar multiplication

array([3, 6, 9])

In [22]:
a*b #scalar multiplication


array([ 4, 10, 18])

In [23]:
#Prodotto scalare:

c= np.array([1,0]) 
d= np.array([0,1]) 

e= np.array([1,2,3])
f= np.array([2,4,6]) #combinazione lineare dell'array e (e*2)

#Dot product (prodotto scalare):

print(np.dot(c,d)) # =0 -> prodotto scalare =0, perpendicolari, angolo = 90°
print(np.dot(e,f)) # prodotto scalare positivo & !=0 -> angolo <90°

0
28


In [25]:
e*f

array([ 2,  8, 18])

In [26]:
M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])

#scalar multiplication

M_1 * 10

array([[10, 20],
       [30, 40]])

In [ ]:
#Abbiamo un chiosco allo stadio dove vendiamo:

#Hot dogs cost €1.50
#Coca Cola cost €0.50
#Made a total of €78.50
#Sold 87 hot dogs and Coca Cola combined

#How many Hot Dogs(x) and Coca Cola(y) have been sold?

In [ ]:
# 1.50x + 0.50y = 78.50  (Equation related to cost)

# x + y = 87   (Equation related to the number sold)

In [31]:
a= np.array([[1.50, 0.5], #MATRICE COEFFICIENTI
             [1, 1]])

b= np.array([[78.50], #MATRICE TERMINI NOTI
              [87.0]])
print(a) 
print(b)

[[1.5 0.5]
 [1.  1. ]]
[[78.5]
 [87. ]]


In [ ]:
# AX=b
# inv(A)AX=inv(A)b
# IX=inv(A)b
# X=inv(A)b

In [35]:
#Calculate inverse of A

inv_a= np.linalg.inv(a)
print(inv_a)

[[ 1.  -0.5]
 [-1.   1.5]]


In [37]:
ID= a @ inv_a  #identity matrix @ prodotto matriciale 
ID

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [41]:
ID_2= np.eye(2)
ID_2

array([[1., 0.],
       [0., 1.]])

In [39]:
np.allclose(ID, ID_2) #confrontiamo le 2 matrici identità solo per sicurezza.

True

In [44]:
X= inv_a @ b #matrice delle Soluzioni (valori incognite) X=inv(A)b
X #35 x (quantità hotdog venduti) e 52 y (quantità coca cola venduti)

array([[35.],
       [52.]])